// <auto-generated file>
namespace cardgames.core
{
	public static class L10n
	{
		public const string Lang_NowUsing = "Lang.NowUsing";
		public const string Lang_Select = "Lang.Select";
		public const string Menu_Welcome = "Menu.Welcome";
		public const string Menu_Login = "Menu.Login";
		public const string Menu_AddPlayer = "Menu.AddPlayer";
		public const string Menu_CreateUser = "Menu.CreateUser";
		public const string Menu_LanguageSelect = "Menu.LanguageSelect";
		public const string Menu_RechargeBalance = "Menu.RechargeBalance";
		public const string Menu_ViewLeaderboard = "Menu.ViewLeaderboard";
		public const string Menu_GameSelection = "Menu.GameSelection";
		public const string Menu_Exit = "Menu.Exit";
		public const string Menu_LoggedIn = "Menu.LoggedIn";
		public const string Menu_Back = "Menu.Back";
		public const string Menu_Input_Username = "Menu.Input.Username";
		public const string Menu_Input_Password = "Menu.Input.Password";
		public const string Menu_Loading = "Menu.Loading";
		public const string Leaderboard_Title = "Leaderboard.Title";
		public const string Auth_Name_Preferred = "Auth.Name.Preferred";
		public const string Auth_Username_NotTaken = "Auth.Username.NotTaken";
		public const string Auth_Username_Input = "Auth.Username.Input";
		public const string Auth_Username_Taken = "Auth.Username.Taken";
		public const string Auth_Password_Requirements = "Auth.Password.Requirements";
		public const string Auth_Password_Enter = "Auth.Password.Enter";
		public const string Auth_Login_PlayerFound = "Auth.Login.PlayerFound";
		public const string Auth_Login_PlayerFoundNoBalance = "Auth.Login.PlayerFoundNoBalance";
		public const string Err_GameNotFound = "Err.GameNotFound";
		public const string Err_PlayerNotFound = "Err.PlayerNotFound";
		public const string Err_PasswordNotSecure = "Err.PasswordNotSecure";
		public const string Err_UserDataNotFound = "Err.UserDataNotFound";
		public const string Err_BalanceNotLoaded = "Err.BalanceNotLoaded";
		public const string Err_AlreadyLoggedIn = "Err.AlreadyLoggedIn";
		public const string Util_Yes = "Util.Yes";
		public const string Util_No = "Util.No";
		public const string Util_PressKey = "Util.PressKey";
		public const string User_Ask_Betting = "User.Ask.Betting";
		public const string User_Betting_Info = "User.Betting.Info";
		public const string User_Balance = "User.Balance";
		public const string Info_SavingData = "Info.SavingData";
		public const string Rank_Two = "Rank.Two";
		public const string Rank_Three = "Rank.Three";
		public const string Rank_Four = "Rank.Four";
		public const string Rank_Five = "Rank.Five";
		public const string Rank_Six = "Rank.Six";
		public const string Rank_Seven = "Rank.Seven";
		public const string Rank_Eight = "Rank.Eight";
		public const string Rank_Nine = "Rank.Nine";
		public const string Rank_Ten = "Rank.Ten";
		public const string Rank_Jack = "Rank.Jack";
		public const string Rank_Queen = "Rank.Queen";
		public const string Rank_King = "Rank.King";
		public const string Rank_Ace = "Rank.Ace";
		public const string Suit_Hearts = "Suit.Hearts";
		public const string Suit_Diamonds = "Suit.Diamonds";
		public const string Suit_Clubs = "Suit.Clubs";
		public const string Suit_Spades = "Suit.Spades";
		public const string Card_Of = "Card.Of";
		public const string Blackjack_Hit = "Blackjack.Hit";
		public const string Blackjack_Stand = "Blackjack.Stand";
		public const string Blackjack_Double = "Blackjack.Double";
		public const string Blackjack_PlayerHand = "Blackjack.PlayerHand";
		public const string Blackjack_HandValueInfo = "Blackjack.HandValueInfo";
		public const string Blackjack_Player_Lost = "Blackjack.Player.Lost";
		public const string Blackjack_Player_LostDouble = "Blackjack.Player.LostDouble";
		public const string Blackjack_Player_Won = "Blackjack.Player.Won";
		public const string Blackjack_Player_WonDouble = "Blackjack.Player.WonDouble";
		public const string Blackjack_Player_Drew = "Blackjack.Player.Drew";
		public const string Blackjack_Player_WinSummary = "Blackjack.Player.WinSummary";
		public const string Blackjack_Player_WinSummary_Doubled = "Blackjack.Player.WinSummary.Doubled";
		public const string Blackjack_Dealer_FaceUpCard = "Blackjack.Dealer.FaceUpCard";
		public const string Blackjack_Player_BustChance = "Blackjack.Player.BustChance";
		public const string Blackjack_Player_WentBust = "Blackjack.Player.WentBust";
	}
}