@startuml
abstract class "GameBase`1"<TPlayer> {
    - # GameBase()
    + <<readonly>> GameName : string
    + {abstract} PlayGame(players:List<TPlayer>) : List<Player>
    - # {abstract} PlayTurn() : void
    - # {abstract} EndGame() : void
    + LoadGame() : void
}
@enduml
