@startuml
struct Money {
    - <<readonly>> _value : decimal
    + Money(value:decimal)
    + Value : decimal <<get>>
    + CompareTo(other:Money) : int
    + Equals(other:Money) : bool
    + <<override>> Equals(obj:object) : bool
    + <<override>> GetHashCode() : int
    + <<override>> ToString() : string
    + ToString(format:string, formatProvider:IFormatProvider) : string
}
class "IComparable`1"<T> {
}
class "IEquatable`1"<T> {
}
"IComparable`1" "<Money>" <|-- Money
"IEquatable`1" "<Money>" <|-- Money
IFormattable <|-- Money
@enduml
