@startuml
class Player {
    - <<const>> USER_FOLDER_PATH : string = "..\\..\\..\\data\\user\\"
    - # name : string
    - # uname : string
    - # rechargeCount : int
    + GetName() : string
    + GetUsername() : string
    + GetBalance() : Money
    + Player(create:bool)
    + Player(name:string)
    + Player(_name:string, _uname:string, _balance:decimal, _recharges:int)
    - Player(_name:string, _uname:string)
    - SetPreferredName() : void
    - SetUsername() : void
    - SetPassword() : void
    - SavePassword(password:string) : void
    + {static} LogIn(userName:string, password:string) : Player?
    + LogOut() : bool
    - {static} ComputeHash(data:string, saltBytes:byte[], iterations:int) : string
    + {static} GetLeaderboardPlayerData() : Dictionary<string, Money>
    + SaveUserData() : void
    + {static} SavePlayers(players:List<Player>) : void
    + PlaceBet(amountToBet:Money) : void
    + DoubleBet() : void
    + AddToBalance(amountToAdd:Money) : void
    + DeductFromBalance(amountToDeduct:Money) : void
    + DeductBetFromBalance() : Money
    + AddBetToBalance() : Money
    + RechargeBalance() : void
    + GetHand() : List<Card>
    + AddToHand(card:Card) : void
    + AddToHand(cards:List<Card>) : void
    + AddToHand(deck:Deck) : void
    + PlayCard(card:Card) : Card
    + PlayCards(cards:List<Card>) : List<Card>
    + SortHandBySuit() : void
    + SortHandByRank() : void
    + DeselectAllCards() : void
}
class "List`1"<T> {
}
Player o-> "DEFAULT_BALANCE" Money
Player --> "balance" Money
Player --> "Bet" Money
Player o-> "hand<Card>" "List`1"
@enduml
