@startuml
class Util <<static>> {
    - {static} loading : Thread?
    + {static} IsLoading : bool = false
    + {static} UserAgrees() : bool
    + {static} GetChoice(options:string[], selected:int) : int
    + {static} GetPassword() : string
    + {static} ResetColor() : void
    + {static} ResetColour() : void
    + {static} WriteLineBackwards(input:string) : void
    + {static} StartLoading(reason:string) : void
    + {static} FinishLoading() : void
    - {static} LoadingBar(reason:string) : void
    + {static} MaximiseWindow() : void
}
struct Rect {
    + Left : int
    + Top : int
    + Right : int
    + Bottom : int
}
Util o-> "DEFAULT_FOREGROUND" ConsoleColor
Util o-> "DEFAULT_BACKGROUND" ConsoleColor
Util o-> "SELECTED_FOREGROUND" ConsoleColor
Util +-- Rect
@enduml
