@startuml
class BlackjackDealer {
    + Bust : bool <<get>>
    + HandValue : int <<get>>
    + AddCardToHand(card:Card) : void
    - CalculateHandValue() : int
    + Play(deck:Deck) : void
}
class "List`1"<T> {
}
BlackjackDealer o-> "Hand<Card>" "List`1"
BlackjackDealer --> "PublicCard" Card
@enduml
