@startuml
class BlackjackGame {
    + <<const>> DECKCOUNT : int = 6
    + BlackjackGame()
    + <<override>> PlayGame(players:List<Player>) : List<Player>
    - # <<override>> PlayTurn() : void
    - DisplayBlackjackData(player:BlackjackPlayer, state:BlackjackState) : void
    - # <<override>> EndGame() : void
    - CheckWinners() : void
}
class "GameBase`1"<T> {
}
"GameBase`1" "<Player>" <|-- BlackjackGame
BlackjackGame o-> "State" BlackjackState
@enduml
