using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace cardgames.core.language
{
    internal class LanGen // localisation (L10n) generator; to be run separately from the main program.
    {
        public static void GenerateLocalisations()
        {
            const string LANGUAGE_BASE_DIRECTORY = "..\\..\\..\\lang\\";
            const string GAMES_DIRECTORY = "..\\..\\..\\game\\";
            const string OUTPUT_PATH = "..\\..\\..\\data\\runtime\\L10n.cs";
            const string START_CONTENTS = "// <auto-generated file>\nnamespace cardgames.core\n{\n\tpublic static class L10n\n\t{\n";
            const string END_CONTENTS = "\t}\n}";

            HashSet<string> allKeys = [];


            if (Directory.Exists(LANGUAGE_BASE_DIRECTORY))
            {
                foreach (string? file in Directory.GetFiles(LANGUAGE_BASE_DIRECTORY, "*.json"))
                {
                    ExtractKeys(file, allKeys);
                }
            }

            if (Directory.Exists(GAMES_DIRECTORY))
            {
                foreach (var gameDirectory in Directory.GetDirectories(GAMES_DIRECTORY))
                {
                    string gameLangDirectory = Path.Combine(gameDirectory, "lang");
                    if (Directory.Exists(gameLangDirectory))
                    {
                        foreach (string? file in Directory.GetFiles(gameLangDirectory, "*.json"))
                        {
                            ExtractKeys(file, allKeys);
                        }
                    }
                }
            }

            string fileContents = START_CONTENTS;
            foreach (string key in allKeys) fileContents += $"\t\tpublic const string {key.Replace('.', '_')} = \"{key}\";\n";
            fileContents += END_CONTENTS;
            File.WriteAllText(OUTPUT_PATH, fileContents);
        }

        private static void ExtractKeys(string filePath, HashSet<string> keys)
        {
            string jsonText = File.ReadAllText(filePath);

            var keyMatcher = new System.Text.RegularExpressions.Regex(@"""([^""]+)""\s*:");

            var matches = keyMatcher.Matches(jsonText);

            foreach (System.Text.RegularExpressions.Match match in matches)
            {
                string key = match.Groups[1].Value;
                keys.Add(key);
            }
        }
    }
}
