@startuml
class Program {
    + + Main() : void
}
class Application {
    + +# MAX_PLAYERS : int
    + + Load() : void
    - - LoadDefaultSettings() : void
    - - OnProcessExit(sender:object, e:EventArgs) : void
    - - OnCancelKeyPress(sender:object, e:ConsoleCancelEventArgs) : void
}
class Betting {
    + + BettingMenu(players:List<TPlayer>, betAmounts:decimal[]?) : void
}
enum Suits {
    Hearts= 0x2665,
    Diamonds= 0x2666,
    Clubs= 0x2663,
    Spades= 0x2660,
}
enum Ranks {
    Two= 2,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
    Ten,
    Jack,
    Queen,
    King,
    Ace,
}
class Card {
    + + IsFaceCard : bool
    + + IsFaceUp : bool
    + + IsRed : bool
    + + Value : int
    + + IsSelected : bool
    + + IsHovered : bool
    + + Card(suit:Suits, rank:Ranks)
    + + GetSuitSymbol() : char
    + + GetRankSymbol() : string
    + + GetSuitSymbol(suit:Suits) : char
    + + GetRankSymbol(rank:Ranks) : string
    + + Select() : void
    + + Deselect() : void
    + + ToggleSelect() : void
    + + Hover() : void
    + + Unhover() : void
    + + ToggleHover() : void
    + + GetSelectedCardCount(cards:List<Card>) : int
    + + GetSelectedCards(cards:List<Card>) : List<Card>
    + + DeselectCards(cards:List<Card>) : List<Card>
    + + DeselectCards(deck:Deck) : Deck
    + + TurnFaceUp() : void
    + + TurnFaceDown() : void
    + + ToString() : string
    + + Equals(obj:object?) : bool
    - - Equals(card:Card) : bool
}
class Deck {
    + + Deck()
    + + Clone() : Deck
    + + AddCard(newCard:Card) : void
    + + AddCards(newCards:IEnumerable<Card>) : void
    + + Shuffle() : void
    + + Draw() : Card?
    + + Deal(playerCount:int, cardsPerPlayer:int) : Card[,]
    - - GenerateStandardDeck() : Stack<Card>
    + + AddStandardDecks(count:int) : void
    + + RemoveCard(card:Card) : void
    + + GetCards() : Stack<Card>
    + + GetTopCard() : Card?
    + + GetNthCardFromTop(index:int) : Card?
    + + Count : int
    + + Empty() : Stack<Card>
}
abstract class GameBase<TPlayer> {
    - -# GameBase()
    + + GameName : string
    + + {abstract} PlayGame(players:List<TPlayer>) : List<Player>
    - -# {abstract} PlayTurn() : void
    - -# {abstract} EndGame() : void
    + + LoadGame() : void
}
enum Direction {
    clockwise,
    anticlockwise,
}
class GameState<TPlayer> {
    - -# currentPlayer : int
    + + GameState(_players:IEnumerable<TPlayer>)
    + + GetCurrentPlayer() : TPlayer
    + + NextPlayer() : void
    + + GetPlayerList() : List<TPlayer>
    + + SetDirection(_direction:Direction) : void
    + + GetDeck() : Deck
    + + DrawCard() : Card
    + + Deal(cardsToDrawEach:int) : void
    + + SetupDeck(deckCount:int) : void
    + + ChooseRandomStartingPlayer() : int
}
class Language {
    - -# LANGUAGE_DIRECTORY_PATH : string
    - -# DEFAULT_LANGUAGE_CODE : string
    + + CurrentLanguage : string
    + + SelectLanguage() : void
    - - DetectLanguages() : string[]
    + + Load(languageCode:string) : void
    + + LoadGame(gameName:string) : void
    + + UnloadGame(gameName:string) : void
    - - T(key:string, parameters:Dictionary<string, string>?) : string
    + + T(key:string, parameters:(string Key, string Value)[]) : string
}
class Menu {
    - -# GAMES_FOLDER_PATH : string
    - -# LEADERBOARD_PATH : string
    + + StartupMenu(players:List<Player>?) : List<Player>
    - - RechargeBalance(players:List<Player>) : void
    + + GameMenu() : GameBase<Player>?
    - - GetGameChoice(games:Dictionary<string, string>, options:string[], selected:int) : object?
    - - ImportGames() : Dictionary<string, string>
    - - GetGame(gameClassName:string) : object?
    - - LeaderboardMenu() : void
    + + UpdateLeaderboard() : void
}
struct Money {
    - - _value : decimal
    + + Money(value:decimal)
    + + Value : decimal
    + + CompareTo(other:Money) : int
    + + Equals(other:Money) : bool
    + + Equals(obj:object) : bool
    + + GetHashCode() : int
    + + ToString() : string
    + + ToString(format:string, formatProvider:IFormatProvider) : string
}
class Player {
    - -# USER_FOLDER_PATH : string
    - -# name : string
    - -# uname : string
    - -# rechargeCount : int
    + + GetName() : string
    + + GetUsername() : string
    + + GetBalance() : Money
    + + Player(create:bool)
    + + Player(name:string)
    + + Player(_name:string, _uname:string, _balance:decimal, _recharges:int)
    - - Player(_name:string, _uname:string)
    - - SetPreferredName() : void
    - - SetUsername() : void
    - - SetPassword() : void
    - - SavePassword(password:string) : void
    + + LogIn(userName:string, password:string) : Player?
    + + LogOut() : bool
    - - ComputeHash(data:string, saltBytes:byte[], iterations:int) : string
    + + GetLeaderboardPlayerData() : Dictionary<string, Money>
    + + SaveUserData() : void
    + + SavePlayers(players:List<Player>) : void
    + + PlaceBet(amountToBet:Money) : void
    + + DoubleBet() : void
    + + AddToBalance(amountToAdd:Money) : void
    + + DeductFromBalance(amountToDeduct:Money) : void
    + + DeductBetFromBalance() : Money
    + + AddBetToBalance() : Money
    + + RechargeBalance() : void
    + + GetHand() : List<Card>
    + + AddToHand(card:Card) : void
    + + AddToHand(cards:List<Card>) : void
    + + AddToHand(deck:Deck) : void
    + + PlayCard(card:Card) : Card
    + + PlayCards(cards:List<Card>) : List<Card>
    + + SortHandBySuit() : void
    + + SortHandByRank() : void
    + + DeselectAllCards() : void
}
class Util {
    - - loading : Thread?
    + + IsLoading : bool
    + + UserAgrees() : bool
    + + GetChoice(options:string[], selected:int) : int
    + + GetPassword() : string
    + + ResetColor() : void
    + + ResetColour() : void
    + + WriteLineBackwards(input:string) : void
    + + StartLoading(reason:string) : void
    + + FinishLoading() : void
    - - LoadingBar(reason:string) : void
    + + MaximiseWindow() : void
}
struct Rect {
    + + Left : int
    + + Top : int
    + + Right : int
    + + Bottom : int
}
class DictionaryExtensions {
    + + AddRange(target:IDictionary<TKey, TValue>, source:IEnumerable<KeyValuePair<TKey, TValue>>) : void
    + + RemoveRange(target:IDictionary<TKey, TValue>, source:IEnumerable<KeyValuePair<TKey, TValue>>) : void
}
class StackExtensions {
    + + Shuffle(stack:Stack<T>) : void
    + + RemoveFirstOccurrence(stack:Stack<T>, itemToRemove:T) : void
    + + Empty(collection:Stack<T>) : Stack<T>
}
abstract class NaturalLanguageParser {
    + + ImportMap(path:string) : Dictionary<string, TEnum>
    - -# ExportMap(map:Dictionary<string, TEnum>, path:string) : void
    - -# TryFindMatch(token:string, map:Dictionary<string, T>, value:T) : bool
    - -# TryFuzzyMatch(token:string, map:Dictionary<string, T>, value:T) : bool
    - -# NormaliseInput(input:string) : string
    - -# Levenshtein(string1:string, string2:string) : int
}
class BlackjackDealer {
    + + Bust : bool
    + + HandValue : int
    + + AddCardToHand(card:Card) : void
    - - CalculateHandValue() : int
    + + Play(deck:Deck) : void
}
class BlackjackGame {
    + +# DECKCOUNT : int
    + + BlackjackGame()
    + + PlayGame(players:List<Player>) : List<Player>
    - -# PlayTurn() : void
    - - DisplayBlackjackData(player:BlackjackPlayer, state:BlackjackState) : void
    - -# EndGame() : void
    - - CheckWinners() : void
}
enum WinStates {
    Lost,
    Drew,
    Won,
}
class BlackjackPlayer {
    + + Bust : bool
    + + Standing : bool
    + + Doubled : bool
    + + HasPlayed : bool
    + + HandValue : int
    + + CardsInHand : int
    + + ConvertTo(player:Player) : BlackjackPlayer
    + + ConvertTo(players:List<Player>) : List<BlackjackPlayer>
    + + ConvertFrom(blackjackPlayer:BlackjackPlayer) : Player
    + + ConvertFrom(blackjackPlayers:List<BlackjackPlayer>) : List<Player>
    + + GoBust() : void
    + + Stand() : void
    + + Double() : void
    - - CalculateHandValue() : int
    + + GetBustChance(state:BlackjackState) : double
    + + EndTurn() : void
    + + Win() : void
    + + Draw() : void
    + + Lose() : void
}
class BlackjackState {
    + + BlackjackState(_players:List<BlackjackPlayer>)
    + + Deal(cardsToDrawEach:int) : void
    + + PlayerTurnsFinished() : bool
}
class CheatDisplay {
    + +# CARD_WIDTH : int
    + +# CARD_HEIGHT : int
    + + DisplayScrollMenu(cards:List<Card>, currentCardIndex:int) : void
    - - DisplayThreeCardView(cards:List<Card>, currentCardIndex:int) : void
    + + BigCard(card:Card) : void
    - - ShortCard(rightSide:bool, card:Card?) : void
    - - SelectedCards(cards:List<Card>) : void
    - - OwnedCards(cards:List<Card>) : void
}
class CheatGame {
    - - CANCEL_COUNTDOWN : bool
    + +# DECKCOUNT : int
    + + CheatGame()
    + + PlayGame(players:List<Player>) : List<Player>
    - - CheckWinners() : void
    - - DisplayCallCheatMenu(displayDurationSeconds:int) : void
    - - CheatCalled(accused:CheatPlayer, accuser:CheatPlayer, playedCards:List<Card>, rankClaimed:Ranks?) : void
    - - DidCheat(playedCards:List<Card>, rankClaimed:Ranks?) : bool
    - -# PlayTurn() : void
    - -# EndGame() : void
    - - ScrollMenu(cards:List<Card>) : void
}
class CheatParser {
    + + CheatParser()
    + + ImportMaps(rankMapPath:string, suitMapPath:string) : void
    + + TryParseCard(input:string, card:Card?) : bool
    + + TryParseRank(input:string, rank:Ranks?) : bool
}
class CheatPlayer {
    - - won : bool
    + + HasWon() : bool
    + + Win() : void
    + + ConvertTo(player:Player) : CheatPlayer
    + + ConvertTo(players:List<Player>) : List<CheatPlayer>
    + + ConvertFrom(cheatPlayer:CheatPlayer) : Player
    + + ConvertFrom(cheatPlayers:List<CheatPlayer>) : List<Player>
}
class CheatState {
    - - gameOver : bool
    + + IsGameOver() : bool
    + + GameOver() : void
    + + Discard(card:Card) : void
    + + Discard(cards:List<Card>) : int
    + + Beep() : void
    + + PrepareDeck() : void
    + + PlayerPicksUpPile(playerToPickUp:Player) : void
}
class KlondikeDisplay {
    + +# CARD_WIDTH : int
    + +# CARD_HEIGHT : int
    - - x : int
    - - y : int
    - - startX : int
    - - startY : int
    - - changesMade : bool
    - - totallyRedrawScreen : bool
    - - BigCardOutline(suit:Suits?) : void
    - - BigCard(card:Card, justDisplayTopLine:bool, highlightAsTarget:bool) : void
    + + DisplayKlondikeMenu(state:KlondikeState) : void
    - - DisplayGameScreen(state:KlondikeState) : void
    - - DisplayDrawSection(state:KlondikeState) : void
    - - DisplayCardStacks(state:KlondikeState) : void
    - - DisplaySuitStacks(state:KlondikeState) : void
    - - DisplayInformation(state:KlondikeState) : void
    - - DisplayIndividualCardStack(cardStack:Stack<Card>, isEmptyAndHovered:bool, displayTopCardAsTarget:bool) : void
    - - HandleInput(state:KlondikeState) : void
    - - HandleCardStacksInput(state:KlondikeState, inputKey:ConsoleKeyInfo) : void
    - - HandleDrawPilesInput(state:KlondikeState, inputKey:ConsoleKeyInfo) : void
    - - HandleSuitStacksInput(state:KlondikeState, inputKey:ConsoleKeyInfo) : void
    - - HandleMoveSelectionInput(state:KlondikeState, inputKey:ConsoleKeyInfo) : void
    - - HandleConfirmationInput(state:KlondikeState) : void
    - - HandleDebugInput(state:KlondikeState, inputKey:ConsoleKeyInfo) : void
}
class KlondikeGame {
    + + KlondikeGame()
    + + PlayGame(_players:List<Player>) : List<Player>
    - -# PlayTurn() : void
    - -# EndGame() : void
}
class KlondikeMove {
    + + KlondikeMove(type:MoveType, targetIndex:int, card:Card?)
    + + KlondikeMove(type:MoveType, targetIndex:int, startingLocation:KlondikeState.Location?, startingStackIndex:int, startingCardIndex:int, card:Card?)
    + + KlondikeMove(type:MoveType, targetIndex:int, startingLocation:KlondikeState.Location?, card:Card?)
    + + KlondikeMove(type:MoveType, card:Card?)
    + + StartingStackIndex : int
    + + StartingCardIndex : int
    + + TargetIndex : int
    + + ToString() : string
}
enum MoveType {
    ToSuitStack,
    ToCardStack,
    DrawCard,
    ResetDrawPile,
    TurnCard,
}
class KlondikePlayer {
    + + ConvertTo(player:Player) : KlondikePlayer
    + + ConvertTo(players:List<Player>) : List<KlondikePlayer>
    + + ConvertFrom(kdp:KlondikePlayer) : Player
    + + ConvertFrom(klondikePlayers:List<KlondikePlayer>) : List<Player>
}
class KlondikeSolver {
    + + Solve(state:KlondikeState, visitedStates:HashSet<KlondikeState>, solutionPath:List<KlondikeMove>) : List<KlondikeMove>?
    + + SolveIteratively(initialState:KlondikeState) : List<KlondikeMove>?
    + + SolveWithDepthLimit(initialState:KlondikeState, maxDepth:int) : List<KlondikeMove>?
    - - DepthFirstSearch(state:KlondikeState, maxDepth:int, currentDepth:int, visitedStates:HashSet<KlondikeState>) : List<KlondikeMove>?
    + + SolveWithMemoryLimit(initialState:KlondikeState, maxVisitedStates:int, timeoutMs:int) : List<KlondikeMove>?
    - - MoveHeuristic(move:KlondikeMove) : int
}
class KlondikeState {
    + + SelectedCardStack : int
    + + SelectedSuitStack : int
    + + SelectedCardInStack : int
    + + HasBeenSolved : bool
    + + SelectedMoveIndex : int
    + + TimesDrawPileRestocked : int
    + + Score : int
    + + IsInCardStacks() : bool
    + + IsInDrawPile() : bool
    + + IsInSuitStacks() : bool
    + + IsInLeftmostSuitStack() : bool
    + + IsInFaceUpDrawPile() : bool
    + + IsInFaceDownDrawPile() : bool
    + + GetMoves() : List<KlondikeMove>
    + + MoveStackSelectionLeft() : bool
    + + MoveStackSelectionRight() : bool
    + + MoveCardSelectionUp() : bool
    + + MoveCardSelectionDown() : bool
    + + MoveCardSelectionToTop() : bool
    + + MoveToDrawPile() : bool
    + + MoveToFaceDownDrawPile() : bool
    + + MoveToFaceUpDrawPile() : bool
    + + MoveToCardStacks() : bool
    + + MoveToSuitStacks() : bool
    + + MoveSuitStackRight() : bool
    + + MoveSuitStackLeft() : bool
    + + SelectNthMove(n:int) : bool
    + + SelectNextMove() : bool
    + + SelectPreviousMove() : bool
    + + ResetMoves() : bool
    + + ScoreDrawnToCardStacks() : void
    + + ScoreDrawnToSuitStacks() : void
    + + ScoreCardStacksToSuitStacks() : void
    + + ScoreTurnOverCardStacksCard() : void
    + + ScoreSuitStacksToCardStacks() : void
    + + ScoreRestockDrawPile() : void
    + + MarkDrawPileAsRestocked() : void
    + + SetupCards() : void
    + + ResetGame() : void
    + + Clone() : KlondikeState
    - - InitialiseSuitStackOrder() : void
    - - GetCardStack(index:int) : Stack<Card>
    + + GetCardStacks() : Stack<Card>[]
    + + GetCurrentCard() : Card?
    + + GetTopCardFromStack(index:int) : Card?
    + + GetNthCardFromCardStack(cardStackIndex:int, n:int) : Card?
    + + GetCardAtLocation(location:Location, cardIndex:int, stackIndex:int, drawPileRegion:DrawPileRegion?) : Card?
    + + HoverCurrentCard() : void
    + + UnhoverCurrentCard() : void
    + + GetNthCardAndAboveFromStack(currentStack:int, currentCardInStack:int) : List<Card>
    + + AddCardToDrawnCards(card:Card) : void
    + + GetDrawnCards() : Stack<Card>
    + + GetNextRankForSuitStack(suit:Suits) : Ranks?
    + + AddRankBackToNextSuitStackList(suit:Suits, rank:Ranks) : void
    + + GetTopCardFromSuitStack(suit:Suits) : Card
    + + UpdateMoves() : void
    + + GetPossibleMovesForCurrentCard() : List<KlondikeMove>
    + + GetMovesByLocation(location:Location, cardIndex:int, cardStackIndex:int, drawRegion:DrawPileRegion?) : List<KlondikeMove>
    + + GetAllPossibleMoves() : List<KlondikeMove>
    + + TryMakeSelectedMove() : bool
    + + TryMakeMove(move:KlondikeMove) : bool
    + + CheckSolveState() : bool
    + + Equals(obj:object?) : bool
    + + Equals(other:KlondikeState?) : bool
    + + GetHashCode() : int
}
enum Location {
    CardStacks,
    SuitStacks,
    DrawPiles,
}
enum DrawPileRegion {
    FaceDown,
    FaceUp,
}

Program --- Application
Application o-- Player
Application --- Menu
Application --- GameBase
Application --- Language
Application --- Util
Betting --- Player
Card --- Suits
Card --- Ranks
Deck *-- Card
GameBase --- Player
GameBase <|-- BlackjackGame
GameBase <|-- CheatGame
GameBase <|-- KlondikeGame
GameState *-- Deck
GameState o-- Player
GameState --- Direction
Language --- Menu
Menu --- Player
Menu --- GameBase
Player o-- Card
Player --- Money
Util --- Rect
NaturalLanguageParser <|-- CheatParser
CheatParser *-- Ranks
CheatParser *-- Suits
CheatParser --- Card
BlackjackDealer o-- Card
BlackjackDealer --- Deck
BlackjackPlayer <|-- Player
BlackjackPlayer --- WinStates
BlackjackPlayer --- BlackjackState
BlackjackState <|-- GameState
BlackjackState *-- BlackjackDealer
BlackjackGame *-- BlackjackState
CheatPlayer <|-- Player
CheatState <|-- GameState
CheatState *-- Deck
CheatState o-- Card
CheatState o-- Player
CheatGame *-- CheatState
CheatDisplay --- Card
KlondikePlayer <|-- Player
KlondikeState <|-- GameState
KlondikeState o-- Card
KlondikeState *-- KlondikeMove
KlondikeState --- Suits
KlondikeState --- Location
KlondikeState --- DrawPileRegion
KlondikeState --- KlondikePlayer
KlondikeMove --- MoveType
KlondikeMove --- KlondikeState
KlondikeMove --- Card
KlondikeGame *-- KlondikeState
KlondikeDisplay --- KlondikeState
KlondikeDisplay --- Card
KlondikeSolver --- KlondikeState
KlondikeSolver --- KlondikeMove
@enduml