@startuml
class KlondikeSolver <<static>> {
    + {static} Solve(state:KlondikeState, visitedStates:HashSet<KlondikeState>, solutionPath:List<KlondikeMove>) : List<KlondikeMove>?
    + {static} SolveIteratively(initialState:KlondikeState) : List<KlondikeMove>?
    + {static} SolveWithDepthLimit(initialState:KlondikeState, maxDepth:int) : List<KlondikeMove>?
    - {static} DepthFirstSearch(state:KlondikeState, maxDepth:int, currentDepth:int, visitedStates:HashSet<KlondikeState>) : List<KlondikeMove>?
    + {static} SolveWithMemoryLimit(initialState:KlondikeState, maxVisitedStates:int, timeoutMs:int) : List<KlondikeMove>?
    - {static} MoveHeuristic(move:KlondikeMove) : int
}
@enduml
