@startuml
class KlondikeState {
    + SelectedCardStack : int <<get>>
    + SelectedSuitStack : int <<get>>
    + SelectedCardInStack : int <<get>>
    + HasBeenSolved : bool <<get>>
    + SelectedMoveIndex : int <<get>>
    + TimesDrawPileRestocked : int <<get>>
    + Score : int <<get>>
    + IsInCardStacks() : bool
    + IsInDrawPile() : bool
    + IsInSuitStacks() : bool
    + IsInLeftmostSuitStack() : bool
    + IsInFaceUpDrawPile() : bool
    + IsInFaceDownDrawPile() : bool
    + GetMoves() : List<KlondikeMove>
    + MoveStackSelectionLeft() : bool
    + MoveStackSelectionRight() : bool
    + MoveCardSelectionUp() : bool
    + MoveCardSelectionDown() : bool
    + MoveCardSelectionToTop() : bool
    + MoveToDrawPile() : bool
    + MoveToFaceDownDrawPile() : bool
    + MoveToFaceUpDrawPile() : bool
    + MoveToCardStacks() : bool
    + MoveToSuitStacks() : bool
    + MoveSuitStackRight() : bool
    + MoveSuitStackLeft() : bool
    + SelectNthMove(n:int) : bool
    + SelectNextMove() : bool
    + SelectPreviousMove() : bool
    + ResetMoves() : bool
    + ScoreDrawnToCardStacks() : void
    + ScoreDrawnToSuitStacks() : void
    + ScoreCardStacksToSuitStacks() : void
    + ScoreTurnOverCardStacksCard() : void
    + ScoreSuitStacksToCardStacks() : void
    + ScoreRestockDrawPile() : void
    + MarkDrawPileAsRestocked() : void
    + SetupCards() : void
    + ResetGame() : void
    + Clone() : KlondikeState
    - InitialiseSuitStackOrder() : void
    - GetCardStack(index:int) : Stack<Card>
    + GetCardStacks() : Stack<Card>[]
    + GetCurrentCard() : Card?
    + GetTopCardFromStack(index:int) : Card?
    + GetNthCardFromCardStack(cardStackIndex:int, n:int) : Card?
    + GetCardAtLocation(location:Location, cardIndex:int, stackIndex:int, drawPileRegion:DrawPileRegion?) : Card?
    + HoverCurrentCard() : void
    + UnhoverCurrentCard() : void
    + GetNthCardAndAboveFromStack(currentStack:int, currentCardInStack:int) : List<Card>
    + AddCardToDrawnCards(card:Card) : void
    + GetDrawnCards() : Stack<Card>
    + GetNextRankForSuitStack(suit:Suits) : Ranks?
    + AddRankBackToNextSuitStackList(suit:Suits, rank:Ranks) : void
    + GetTopCardFromSuitStack(suit:Suits) : Card
    + UpdateMoves() : void
    + GetPossibleMovesForCurrentCard() : List<KlondikeMove>
    + GetMovesByLocation(location:Location, cardIndex:int, cardStackIndex:int, drawRegion:DrawPileRegion?) : List<KlondikeMove>
    + GetAllPossibleMoves() : List<KlondikeMove>
    + TryMakeSelectedMove() : bool
    + TryMakeMove(move:KlondikeMove) : bool
    + CheckSolveState() : bool
    + <<override>> Equals(obj:object?) : bool
    + Equals(other:KlondikeState?) : bool
    + <<override>> GetHashCode() : int
}
class "List`1"<T> {
}
class "GameState`1"<T> {
}
class "Stack`1"<T> {
}
enum Location {
    CardStacks,
    SuitStacks,
    DrawPiles,
}
enum DrawPileRegion {
    FaceDown,
    FaceUp,
}
"GameState`1" "<KlondikePlayer>" <|-- KlondikeState
KlondikeState o-> "drawnCards<Card>" "Stack`1"
KlondikeState --> "CurrentLocation" Location
KlondikeState --> "CurrentDrawPileRegion" DrawPileRegion
KlondikeState o-> "Moves<KlondikeMove>" "List`1"
KlondikeState +-- Location
KlondikeState +-- DrawPileRegion
@enduml
