@startuml
class KlondikeDisplay <<static>> {
    + <<const>> CARD_WIDTH : int = 11
    + <<const>> CARD_HEIGHT : int = 7
    - {static} x : int
    - {static} y : int
    - {static} startX : int
    - {static} startY : int
    - {static} changesMade : bool = true
    - {static} totallyRedrawScreen : bool = true
    - {static} BigCardOutline(suit:Suits?) : void
    - {static} BigCard(card:Card, justDisplayTopLine:bool, highlightAsTarget:bool) : void
    + {static} DisplayKlondikeMenu(state:KlondikeState) : void
    - {static} DisplayGameScreen(state:KlondikeState) : void
    - {static} DisplayDrawSection(state:KlondikeState) : void
    - {static} DisplayCardStacks(state:KlondikeState) : void
    - {static} DisplaySuitStacks(state:KlondikeState) : void
    - {static} DisplayInformation(state:KlondikeState) : void
    - {static} DisplayIndividualCardStack(cardStack:Stack<Card>, isEmptyAndHovered:bool, displayTopCardAsTarget:bool) : void
    - {static} HandleInput(state:KlondikeState) : void
    - {static} HandleCardStacksInput(state:KlondikeState, inputKey:ConsoleKeyInfo) : void
    - {static} HandleDrawPilesInput(state:KlondikeState, inputKey:ConsoleKeyInfo) : void
    - {static} HandleSuitStacksInput(state:KlondikeState, inputKey:ConsoleKeyInfo) : void
    - {static} HandleMoveSelectionInput(state:KlondikeState, inputKey:ConsoleKeyInfo) : void
    - {static} HandleConfirmationInput(state:KlondikeState) : void
    - {static} HandleDebugInput(state:KlondikeState, inputKey:ConsoleKeyInfo) : void
}
@enduml
